In [3]:
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])

concat_array=np.concatenate((array1,array2))
print("concat_array:",concat_array)

concat_array: [1 2 3 4 5 6]


In [7]:
array2d_1=np.array([[1,2,3],[4,5,6]])
array2d_2=np.array([[7,8,9],[10,11,12],[13,14,15]])
v = np.vstack((array2d_1,array2d_2))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [12]:
array2d_1=np.array([[1,2,3],[4,5,6]])
array2d_2=np.array([[7,8,9],[10,11,12]])
h = np.hstack((array2d_1,array2d_2))
print(h)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
