In [4]:
# reshape a 1D array to a 2D array
import numpy as np

#create  a 1D array
array_1D=np.array([1,2,3,4,5,6])
print("array 1D :",array_1D)
print("shape of array1D : ",array_1D.shape)

array 1D : [1 2 3 4 5 6]
shape of array1D :  (6,)


In [6]:
#convert the 1D array to 2D
array_2D= array_1D.reshape((2,3))
print("array 2D :\n",array_2D)
print("shape of array2D : ",array_2D.shape)

array 2D :
 [[1 2 3]
 [4 5 6]]
shape of array2D :  (2, 3)


In [10]:
# Example 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Desired shape of the 3D array (for example, 2 x 3 x 2)
a, b, c = 2, 3, 2

# Reshaping the array
arr_3d = arr_1d.reshape(a, b, c)

print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
# reshape a 2D array to a 1D array
array_1D_back=array_2D.reshape(6)
print("array back to 1D:",array_1D_back)

array back to 1D: [1 2 3 4 5 6]


In [14]:
# reshape a 2D array to a 1D array
array_1D_back=array_2D.reshape(1,6)
print("array back to 1D:",array_1D_back)

array back to 1D: [[1 2 3 4 5 6]]


In [15]:
# reshape a 2D array to a 1D array
array_1D_back=array_2D.reshape(-1)
print("array back to 1D:",array_1D_back)

array back to 1D: [1 2 3 4 5 6]


In [17]:
# reshape a 2D array to a 1D array
array_1D_back=array_2D.reshape(-1)
print("array back to 1D:",array_1D_back)

array back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]
