In [5]:
import numpy as np
#iterations
import numpy as np
#for-in loop
#1d Array
array_1d =np.array([1,2,3,4,5,6])
#iterate the elements in this array
print("Array_1d: ", array_1d)

for elements in array_1d:
   print(elements)




Array_1d:  [1 2 3 4 5 6]
1
2
3
4
5
6


In [14]:
array_2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:", array_2D)
print("\n")
#iterate 2D array
for rows in array_2D:
    print(rows)
    for elements in rows: 
         print(elements)


2D array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


In [15]:
for elements in np.nditer(array_2D): 
    print(elements)

1
2
3
4
5
6
7
8
9


In [17]:
#iterate the elemnts with index
for index, element in np.ndenumerate(array_2D):
     print(f"Index: {index}, Element {element}")

Index: (0, 0), Element 1
Index: (0, 1), Element 2
Index: (0, 2), Element 3
Index: (1, 0), Element 4
Index: (1, 1), Element 5
Index: (1, 2), Element 6
Index: (2, 0), Element 7
Index: (2, 1), Element 8
Index: (2, 2), Element 9
