In [2]:
import numpy as np
#split in numpy

array =np.array([1,2,3,4,5,6,7,8,9])

split_array=np.split(array,3)
print("original array:",array)
print("split array:",split_array)

original array: [1 2 3 4 5 6 7 8 9]
split array: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [3]:
#multi dimentional
#horziontally and vertically
array_2d = np.array([[1,2,3], [4,5,6,], [7,8,9], [10,11,12]])
print(array_2d)
vsplit_array = np.vsplit(array_2d, 2)
print("vsplited array: ", vsplit_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
vsplited array:  [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [7]:
# array_2d = np.array([[1,2,3], [4,5,6,]])
hsplit_array = np.hsplit(array_2d, 3)
print("hsplited array: \n", hsplit_array)

hsplited array: 
 [array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [ ]:
array_2d=np.array([[1,2,3],[4,5,6]])
vsplit_array=np.vsplit(array_2d,2)