In [1]:
import numpy as np

# Example array
arr = np.array([0, 1, 2, 0, 3, 0, 4])

# Count non-zero values
non_zero_count = np.count_nonzero(arr)
print(f"Number of non-zero values: {non_zero_count}")


Number of non-zero values: 4


In [2]:
# Create an empty array of shape (3, 3)
empty_array = np.empty((3, 3))
print("Empty array:")
print(empty_array)

# Create a full array of shape (3, 3) with all elements as 7
full_array = np.full((3, 3), 7)
print("\nFull array:")
print(full_array)


Empty array:
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23047842e-307 2.22526399e-307 6.23053614e-307]
 [7.56592338e-307 9.34588061e-307 3.62651150e-317]]

Full array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [3]:
# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the number of rows and columns
rows, cols = matrix.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {cols}")


Number of rows: 3
Number of columns: 3


In [4]:
# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Sum of all values in the matrix
matrix_sum = np.sum(matrix)
print(f"Sum of values in the matrix: {matrix_sum}")


Sum of values in the matrix: 45


In [5]:
# Example 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diagonal_sum_3x3 = np.trace(matrix_3x3)
print(f"Sum of diagonal elements (3x3): {diagonal_sum_3x3}")

# Example 4x4 matrix
matrix_4x4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
diagonal_sum_4x4 = np.trace(matrix_4x4)
print(f"Sum of diagonal elements (4x4): {diagonal_sum_4x4}")


Sum of diagonal elements (3x3): 15
Sum of diagonal elements (4x4): 34


In [6]:
# Example matrix
matrix = np.array([[1, 2], [3, 4]])

# Inverse of the matrix
matrix_inverse = np.linalg.inv(matrix)
print("Inverse of the matrix:")
print(matrix_inverse)


Inverse of the matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
# Example matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
matrix_product = np.dot(matrix_a, matrix_b)
print("Matrix multiplication result:")
print(matrix_product)


Matrix multiplication result:
[[19 22]
 [43 50]]


In [8]:
# Example matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Maximum value
max_value = np.max(matrix)
print(f"Maximum value: {max_value}")

# Minimum value
min_value = np.min(matrix)
print(f"Minimum value: {min_value}")


Maximum value: 9
Minimum value: 1


In [9]:
# Example matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Adding matrices
matrix_sum = np.add(matrix_a, matrix_b)
print("Sum of matrices:")
print(matrix_sum)

# Subtracting matrices
matrix_diff = np.subtract(matrix_a, matrix_b)
print("Difference of matrices:")
print(matrix_diff)


Sum of matrices:
[[ 6  8]
 [10 12]]
Difference of matrices:
[[-4 -4]
 [-4 -4]]


In [10]:
# Example array
arr = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Count frequency of unique values
unique, counts = np.unique(arr, return_counts=True)
frequency = dict(zip(unique, counts))
print("Frequency of unique values:")
print(frequency)


Frequency of unique values:
{1: 1, 2: 2, 3: 3, 4: 4}
