In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [4]:
#create an 1D array
array_1D=np.array([1,2,3,4,5])
print("1D Array :",array_1D)

1D Array : [1 2 3 4 5]


In [8]:
#create an 2D array
array_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D Array :",array_2D)

2D Array : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
#create a 3D array
array_3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]], 
                     [[13, 14, 15], [16, 17, 18]]])
print("3D Array :\n",array_3D)

3D Array :
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [11]:
#create an array with ones
array_ones=np.ones((2,4))
print("Array with ones:\n",array_ones)

Array with ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
##create an array with zeros
array_zeros=np.zeros((3,3,3))
print("Array with ones:\n",array_zeros)

Array with ones:
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
#array with a particular range
array_range=np.arange(10)
print("array with a range:\n",array_range)

array with a range:
 [0 1 2 3 4 5 6 7 8 9]
